server {
    listen 80;
    server_name localhost;

    root /usr/share/nginx/html;
    index index.html;

    # Obsluga routingu aplikacji SPA - zapobieganie bledom 404
    location / {
        try_files $uri $uri/ /index.html;
    }

    # Przekazywanie zapytan API do backendu w sieci wewnetrznej (Unikanie CORS)
    location /api/ {
        proxy_pass http://backend:3000/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Przekazywanie zapytania wymiany tokenu
    location /auth/ {
        proxy_pass http://backend:3000/auth/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }
}